version: '3'
services:
  backend:
    image: aoushidhi-api:latest
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=your_database_user
      - POSTGRES_PASSWORD=your_database_password
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB=your_database_name
      POSTGRES_USER=your_database_user
      POSTGRES_PASSWORD=your_database_password
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - ./postgresql.sql:/docker-entrypoint-initdb.d/postgresql.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:       # Here we have to keep our postgresql.sql script
